version: "3"
services:
    tomcat:
        container_name: tomcat
        image: tomcat
        volumes:
             - ./Users/apurbamondal/Downloads/abacSpringSecurity-master/sample-Resource-tracker/target/sample-Resource-tracker.war:/usr/local/tomcat/webapps/ROOT.war
        ports:
            - "8180:8080"
        
            docker run -it \
     -p 8080:8080 \
     -v /Users/apurbamondal/Downloads/abacSpringSecurity-master/locus/target/sample-Resource-tracker.war:/usr/local/tomcat/webapps/ROOT.war \
     tomcat
